---
version: 2
project_name: clinar
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# .goreleaser.yaml
brews:
  - repository:
      owner: steffakasid
      name: homebrew-clinar
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: goreleaser@steffen-rumpf.de

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    directory: Formula

    homepage: "https://github.com/steffakasid/clinar"
    description: "This tool can cleanup stale gitlab runners."
    license: "Apache-2.0"
